"""Type stubs for objects module."""

from typing import Any, Dict, List, Tuple

def get_by_id(object_id: int) -> Dict[str, Any] | None: ...
def get_by_name(name: str, exact: bool = False) -> List[Dict[str, Any]]: ...
def get_locations(object_id: int) -> List[Tuple[int, int, int]]: ...
def get_nearby(x: int, y: int, plane: int = 0, radius: int = 10) -> List[Dict[str, Any]]: ...
def search_by_action(action: str) -> List[Dict[str, Any]]: ...
def count_objects() -> int: ...
def count_locations() -> int: ...
def execute_query(query: str, params: tuple = ()) -> List[Dict[str, Any]]: ...
def close() -> None: ...
